name: Release_Unstable

on:
    push:
      tags:
        - "*.*.*"
        - "!*.*.*-beta*"
        - "!*.*.*-rc*"

jobs:
  build_artifact:    
    name: Build and upload artifact
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET SDK 6.0.x and 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
          6.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release /home/runner/work/FasterKvCache/FasterKvCache/FasterKv.Cache.sln
    - name: Pack with dotnet
      env:
        VERSION: ${{ github.ref_name }}
      run: dotnet pack /home/runner/work/FasterKvCache/FasterKvCache/FasterKv.Cache.sln --version-suffix $VERSION -o /home/runner/work/nugetpkgs -c Release --no-build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: nugetpkgs
        path: /home/runner/work/nugetpkgs  

  release_nuget:
      name: Release to Nuget
      needs: build_artifact
      runs-on: ubuntu-latest
  
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v1
          with:
            name: nugetpkgs
        - name: list nugetpkgs
          run: ls nugetpkgs
        - name: Release
          run: |
            for file in nugetpkgs/*.nupkg
            do
              dotnet nuget push $file -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://www.nuget.org/api/v2/package
            done